import Navbar from "@/components/Navbar";
import "./globals.css";
import BodyLayout from "@/components/BodyLayout";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import AOS from "aos";
import "aos/dist/aos.css";

export const metadata = {
  // title: "Nextjs tutorial",
  title: {
    default: "Company-Name ",
    template: "%s | Company-Name",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/logo.jpg" />
      </head>
      <BodyLayout>{children}</BodyLayout>
    </html>
  );
}
